# Generated by Django 4.2.7 on 2026-04-28 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_dashboard_data_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('closed', 'Closed')], default='active', max_length=16)),
                ('scope_snapshot', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=16)),
                ('content', models.TextField()),
                ('rendered_prompt', models.TextField(blank=True)),
                ('context_meta', models.JSONField(blank=True, default=dict)),
                ('intent_label', models.CharField(blank=True, choices=[('DASHBOARD_QUERY', 'Dashboard query'), ('GREETING_SMALLTALK', 'Greeting or smalltalk'), ('OUT_OF_SCOPE', 'Out of scope')], max_length=24)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('latency_ms', models.IntegerField(default=0)),
                ('token_input', models.IntegerField(default=0)),
                ('token_output', models.IntegerField(default=0)),
                ('finish_reason', models.CharField(blank=True, max_length=64)),
                ('error_payload', models.JSONField(blank=True, null=True)),
                ('safety_flags', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dashboard.insightconversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
