# Generated by Django 4.2.7 on 2026-05-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_installer_leadsource_team_rep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SunbaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_uuid', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('login_allowed', models.BooleanField(default=False)),
                ('manager_name', models.CharField(blank=True, max_length=255)),
                ('crew_name', models.CharField(blank=True, max_length=255)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunbase_users', to='dashboard.rep')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sunbase_users', to='dashboard.team')),
            ],
            options={
                'ordering': ['full_name', 'external_uuid'],
            },
        ),
    ]
