# Generated by Django 4.2.7 on 2026-05-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_sunbaseuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='setter',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
