# Generated by Django 4.2.7 on 2026-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_project_setter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cxproject',
            name='sunbase_job_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='cio_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='engineering_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='site_survey_approved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='site_survey_submitted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sunbase_job_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
